### ISSUE TITLE
Enclave Question

### ISSUE THREAD

**Issue by nixoid** [mobilecoinofficial/mobilecoin#15]
If I understand the enclave mechanism correctly, it protects the memory of the node from being accessed by other processes. 
Is there anything that prevents an attacker from modifying the code of the node to not use the Enclave without telling other nodes?

**Comment by jcape** [comment]
Hi @nixoid,

When each enclave is loaded, the CPU internally builds a chained SHA256 hash (a "measurement of enclave", or "MRENCLAVE") of the memory pages which contain the enclave binary as they are loaded. In order to perform remote attestation, the MobileCoin consensus enclave uses the `EREPORT` CPU instruction to retrieve that information directly from the hardware. The consensus enclave also injects it's own (runtime-generated) x25519 public key into the report as user data.

Modifying the enclave code would cause that hash to spit out a different value, and the consensus enclaves are configured such that they will only perform key exchange with other enclaves (i.e. establish a secure channel to forward privacy-sensitive information) if the remote measurement matches the local one (i.e. both enclaves are running the same binary).

Similarly, clients use the MRENCLAVE value provided by the "golden" validator enclave binaries to prevent themselves from connecting to bogus enclaves.

**Comment by nixoid** [comment]
ok, I'll rephrase the question:
Why can't someone, theoretically, do all the enclave rituals properly, using VM, while intercepting all unencrypted data before it gets to the enclave, or just reading it from the VM process memory (software-emulated enclave).

Wikipedia says that QEMU managed to successfully emulate SGX: https://en.wikipedia.org/wiki/Software_Guard_Extensions
https://github.com/sslab-gatech/opensgx

**Comment by jcape** [comment]
The "enclave rituals" involve cryptographic authentication of a hardware key burned into the CPU, the Intel Quoting Enclave, and the Intel Attestation Service (IAS).

An enclave running on emulated instructions is presumed not to have access to a valid hardware key, so it would not be able to obtain the OK from IAS. As a result, enclaves running on emulated SGX hadrware would not be able to complete a key exchange with other enclaves, or with clients.

**Comment by nixoid** [comment]
So Intel is the only one who can run a spying nodes (since they are the issuer of the hardware keys).
Okay, this is better than I thought. Thanks again for the detailed explanation.

**Comment by X-Ryl669** [comment]
Yet, IAS has been broken (see [here](https://sgaxe.com/) so I don't understand how this is more secure than not running in an enclave at all. The real security is in the mathematical algorithm (ring protocol, hashing, etc...). IMHO, enclave only add useless complexity. The security should not rely on obscurity and a single vendor. 

What if intel decides, once MobileCoin starts gaining traction, to implement a spyware in its enclave to steal some value from the network ?
