### ISSUE TITLE
authentication of gRPC api

### ISSUE THREAD

**Issue by Ljzn** [mobilecoinofficial/mobilecoin#182]
Hi, would you like to add the authentication method for the gRPC API of the mobilecoind? Since the gRPC channel without SSL/TLS is not secure.

https://grpc.io/docs/guides/auth/ may help.

**Comment by rjwalters** [comment]
Thanks for your comment! You are correct that `mobilecoind` does not offer an authenticated API. Our view is that the `mobilecoind` API should only be used **locally** so that users can avoid sending their private key material to a remote server. 

There will be future applications (like ATMs and point of sale devices) that will require "front end terminal access" to a `mobilecoind` instance on a remote server. In this case, it's probably best to design an authenticated service API to wrap the gRPC interface. This is the approach used by [Lamassu](https://github.com/lamassu), a leading open source cryptocurrency ATM manufacturer.

**Comment by Ljzn** [comment]
Thank you.
