### ISSUE TITLE
mc-testnet-client prints wrong output path of mobilecoind.log

### ISSUE THREAD

**Issue by mad-de** [mobilecoinofficial/mobilecoin#93]
Output:

> Starting local mobilecoind using TestNet servers for source of ledger. Check log at /tmp/mobilenode/mobilecoind.log.

This file / path doesn't exist.
Correct path:
/ (path from which program is run from)

System: Ubuntu 18.04.01 LTS

**Comment by eranrund** [comment]
Heya

Which commit/script/release resulted in this?

Thanks!

**Comment by mad-de** [comment]
“GIT_COMMIT”: “b1fac4c”, “PROFILE”: “release”, “DEBUG”: “false”, “OPT_LEVEL”: “3”, “DEBUG_ASSERTIONS”: “true”, “TARGET_ARCH”: “x86_64”, “TARGET_OS”: “linux”, “TARGET_FEATURE”: “adx,aes,avx,avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,mmx,movbe,pclmulqdq,popcnt,rdrand,rdseed,sse,sse2,sse3,sse4.1,sse4.2,ssse3,xsave,xsavec,xsaveopt,xsaves”, “RUSTFLAGS”: “?”, “SGX_MODE”: “HW”, “IAS_MODE”: “PROD”

**Comment by eranrund** [comment]
Are you referring to the line printed from [here](https://github.com/mobilecoinofficial/mobilecoin/blob/b1fac4c4adcd65b9f0cc353b2b70341aeab1ad65/start-testnet-client.sh#L31)?
If so, I can't see how the print would be incorrect since the print and where the log is redirected to are both `$(pwd)/mobilecoind.log`.

As a side note, this commit would not connect to the test network successfully. You should build from the [v0.1.4](https://github.com/mobilecoinofficial/mobilecoin/tree/v0.1.4) tag - during the test net experiment, the client code and the network code go through breaking changes.

**Comment by hyperreality** [comment]
I can confirm this logfile exists in the correct location on the latest build, this issue can probably be closed.

**Comment by sugargoat** [comment]
Thanks @hyperreality!
